/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante;

import javax.swing.JFileChooser;

/**
 *
 * @author CAMARGO
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        subTitle_1 = new javax.swing.JLabel();
        CadastroFuncionario = new javax.swing.JButton();
        CadastroBebidas = new javax.swing.JButton();
        CadastroEstoque = new javax.swing.JButton();
        CadastroCliente = new javax.swing.JButton();
        CadastroPedidos = new javax.swing.JButton();
        CadastroPratos = new javax.swing.JButton();
        CadastroReservas = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        CadastroFiliais = new javax.swing.JButton();
        CadastroFornecedores = new javax.swing.JButton();
        CadastroIngredientes = new javax.swing.JButton();
        CadastroEntregas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setText("Restaurante");

        subTitle_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        subTitle_1.setText("Cadastros");

        CadastroFuncionario.setText("Cadastro de Funcionário");
        CadastroFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroFuncionarioMouseClicked(evt);
            }
        });

        CadastroBebidas.setText("Cadastro de Bebidas");
        CadastroBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroBebidasActionPerformed(evt);
            }
        });

        CadastroEstoque.setText("Cadastro de Estoque");
        CadastroEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroEstoqueActionPerformed(evt);
            }
        });

        CadastroCliente.setText("Cadastro de Cliente");
        CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteActionPerformed(evt);
            }
        });

        CadastroPedidos.setText("Cadastro de Pedidos");
        CadastroPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroPedidosActionPerformed(evt);
            }
        });

        CadastroPratos.setText("Cadastro de Pratos");
        CadastroPratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroPratosActionPerformed(evt);
            }
        });

        CadastroReservas.setText("Cadastro de Reservas");
        CadastroReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroReservasActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });

        CadastroFiliais.setText("Cadastro de Filiais");
        CadastroFiliais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroFiliaisMouseClicked(evt);
            }
        });

        CadastroFornecedores.setText("Cadastro de Fornecedores");
        CadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroFornecedoresActionPerformed(evt);
            }
        });

        CadastroIngredientes.setText("Cadastro de Ingredientes");
        CadastroIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroIngredientesActionPerformed(evt);
            }
        });

        CadastroEntregas.setText("Cadastro de Entregas");
        CadastroEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroEntregasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(CadastroCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subTitle_1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CadastroFiliais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CadastroFuncionario))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CadastroPratos)
                            .addComponent(CadastroReservas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CadastroFornecedores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CadastroEstoque))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Sair)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CadastroBebidas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CadastroIngredientes))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(CadastroPedidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CadastroEntregas)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(subTitle_1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroCliente)
                    .addComponent(CadastroFiliais)
                    .addComponent(CadastroFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroReservas)
                    .addComponent(CadastroFornecedores)
                    .addComponent(CadastroEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroPratos)
                    .addComponent(CadastroBebidas)
                    .addComponent(CadastroIngredientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroPedidos)
                    .addComponent(CadastroEntregas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(Sair)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteActionPerformed
       dispose();
       new cadastroCliente().setVisible(true);
    }//GEN-LAST:event_CadastroClienteActionPerformed

    private void CadastroEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroEstoqueActionPerformed
        dispose();
        new cadastroEstoque().setVisible(true);
    }//GEN-LAST:event_CadastroEstoqueActionPerformed

    private void CadastroReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroReservasActionPerformed
        dispose();
        new cadastroReserva().setVisible(true);
    }//GEN-LAST:event_CadastroReservasActionPerformed

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
       System.exit(0);
    }//GEN-LAST:event_SairMouseClicked

    private void CadastroFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroFuncionarioMouseClicked
        dispose();
        new cadastroFunc().setVisible(true);
    }//GEN-LAST:event_CadastroFuncionarioMouseClicked

    private void CadastroFiliaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroFiliaisMouseClicked
        dispose();
        new cadastroFilial().setVisible(true);
    }//GEN-LAST:event_CadastroFiliaisMouseClicked

    private void CadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroFornecedoresActionPerformed
        dispose();
        new cadastroFornecedor().setVisible(true);
    }//GEN-LAST:event_CadastroFornecedoresActionPerformed

    private void CadastroPratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroPratosActionPerformed
       dispose();
       new cadastroPrato().setVisible(true);
    }//GEN-LAST:event_CadastroPratosActionPerformed

    private void CadastroBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroBebidasActionPerformed
        dispose();
        new cadastroBebida().setVisible(true);
    }//GEN-LAST:event_CadastroBebidasActionPerformed

    private void CadastroIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroIngredientesActionPerformed
        dispose();
        new cadastroIngrediente().setVisible(true);
    }//GEN-LAST:event_CadastroIngredientesActionPerformed

    private void CadastroEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroEntregasActionPerformed
        dispose();
        new cadastroEntrega().setVisible(true);
    }//GEN-LAST:event_CadastroEntregasActionPerformed

    private void CadastroPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroPedidosActionPerformed
        dispose();
        new cadastroPedido().setVisible(true);
    }//GEN-LAST:event_CadastroPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroBebidas;
    private javax.swing.JButton CadastroCliente;
    private javax.swing.JButton CadastroEntregas;
    private javax.swing.JButton CadastroEstoque;
    private javax.swing.JButton CadastroFiliais;
    private javax.swing.JButton CadastroFornecedores;
    private javax.swing.JButton CadastroFuncionario;
    private javax.swing.JButton CadastroIngredientes;
    private javax.swing.JButton CadastroPedidos;
    private javax.swing.JButton CadastroPratos;
    private javax.swing.JButton CadastroReservas;
    private javax.swing.JButton Sair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel subTitle_1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
